feat: добавить контроллеры для вещей и юзеров
Feirina/java-shareit pull request #1
Opened 2022-10-15 14:08 UTC by Feirina

2022-10-16 07:28 UTC, FanaticFiz requested changes
Финальный комментарий на Я.Практикуме

2022-10-16 07:28 UTC, FanaticFiz commented on pom.xml
> +		<jacoco-maven-plugin.version>0.8.8</jacoco-maven-plugin.version>
Хорошей практикой будет указать кодировку 
`<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>`

2022-10-16 07:28 UTC, FanaticFiz commented on pom.xml
> +		<dependency>
Я советую всем соблюдать некий порядок при объявлении зависимостей.
Сначала "главный" `spring` все его зависимости и всё о нём. 
Потом по степени "тяжеловестности" остальные зависимости

ну и у меня в проекте, например, последними идёт еще одна секция наши собственные библиотеки/модули/контракты.

2022-10-16 07:28 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/booking/Status.java
> +public enum Status {
Будь аккуратна с таким общим названием: `Status`, бывает так что оно пересекается с такими же из других библиотек и это может съесть у тебя некоторое время...
Например, можно случайно заимпортить не то и просидеть часик в отладке не понимая что происходит! )

2022-10-16 07:28 UTC, FanaticFiz commented on pom.xml
Оставлю тут коммент по файлу `application.properties`, так как он не менялся...

Я буду топить за то чтобы ты сразу привыкала к написанию файла свойств для приложения в формате `yaml -> application.yml`
Мне трудно сейчас представить проект в котором до сих пор на него не пересели ))

Соответственно - попрошу тебя этому следовать.

2022-10-16 07:28 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/user/exception/UserEmailException.java
> +public class UserEmailException extends RuntimeException {
Не создавай классы исключений под каждую сущность...
Один общий класс исключений. В данном случае: `ConflictException`.
Бросая его, ты в сообщении будешь писать, какой именно конфликт произошел.

Тоже самое и с `UserNotFoundException` -> `NotFoundException` !

2022-10-16 07:28 UTC, FanaticFiz commented on src/test/java/ru/practicum/shareit/inmemorytests/UserControllerTests.java
> +    private UserDto user = UserDto.builder().build().builder().name("name").email("user@email.com").build();
Ну тут просто небольшой зашквар )))
У тебя пара лишних вызовов билдера посередине этой "лапши"!
Это во-первых.

А во-вторых, чтобы это не называли лапшой, нужно структурировать, чтобы было видно что в итоге мы добавили...

```
    private UserDto user = UserDto.builder()
                                  .name("name")
                                  .email("user@email.com").build();
```

Это же у тебя и в соседнем классе: `ItemControllerTests`

2022-10-16 07:28 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/item/repository/ItemRepository.java
> +    List<Item> getAll();
В репозиториях я бы использовал глагол `find` а в сервисах `get` это дополнительно помогает их разграничивать...

2022-10-16 07:28 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        if (itemRepository.getById(id).isEmpty()) {
Вот этот кусок попробуй отрефакторить, я дам следующие подсказки:
- Воспользуйся тем что у тебя возвращается Optional
- Обрати внимание на то что ты дёргаешь `itemRepository.getById(id)` дважды, зачем-то...

В коде ниже и в другом сервисе я вижу тоже самое.
Я рассчитываю на то что ты и там перепишешь код без дополнительных комментариев с моей стороны ))

2022-10-16 07:28 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +            if (item.getName().toLowerCase().contains(text.toLowerCase()) ||
Очень сложное условие которое не возможно воспринять с первого взгляда... 
Когда такое приходится писать лучше выделить в приватный метод и дать ему хорошее название.
Так чтобы в итоге сама конструкция `if ()` читалась как обычный текст...

Например `if (userIsDrunk())`  ))

2022-10-16 07:28 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/user/repository/UserRepository.java
> +    User update(User user, Long id);
Хорошие интерфейсы...

Но не пойму только почему при update у тебя передаётся еще и id?

Ведь сущность User это уже подразумевает в себе id это же не dto.
И по коду у тебя сначала достаётся пользователь по id из репозитория, т.е. у него точно есть id внутри.
Так что думаю отдельно id всё таки не нужен.

2022-10-16 09:46 UTC, Feirina commented on src/test/java/ru/practicum/shareit/inmemorytests/UserControllerTests.java
> +    private UserDto user = UserDto.builder().build().builder().name("name").email("user@email.com").build();
Да, тут что-то пошло не так у меня)

2022-10-16 15:12 UTC, FanaticFiz approved these changes

2022-10-16 15:12 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/item/repository/ItemRepositoryImpl.java
> +        return findById(item.getId()).get();
Так нельзя... нельзя спросить сразу `get` у `Optional` без проверки что оно там есть.
И об этом тебе должна говорить среда разработки, обращай на это внимание.

Но давай разберемся, а так ли надо тебе делать тут `findById`?

Мне кажется это бессмысленным тут. 
Тебе пришла сущность ты ей обновила, ну ничего же не измениться если ты её сразу и вернешь или ты её дёрнешь через метод...

2022-10-16 15:12 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        Item item = itemRepository.findById(id).orElseThrow(() ->
Да ты молодец, мои замечания поняла правильно и отрефакторила верно!
Но, лучше всего с новой строки начинать новый оператор из цепочки, т.е. так:

```
    @Override
    public ItemDto getById(Long id) {
        Item item = itemRepository.findById(id)
                                  .orElseThrow(() -> new NotFoundException("Вещи с данным id не найдено"));

        return ItemMapper.toItemDto(item);
    }
```

И в лог лучше добавлять те параметры которые ты упоминаешь, т.е.
`new NotFoundException("Не найдена вещь с id: " + id)`

2022-10-16 15:12 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        Item item = itemRepository.findById(id).orElseThrow(() -> new NotFoundException("Вещи с данным id не найдено"));
Даже если помещается в одну строку, я, например, всё равно предпочитаю видеть каждый оператор на отдельной строке.
Но я не настаиваю ))

2022-10-16 15:12 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
> +    private void checkEmailUnique(User user) {
`check` - проверка подразумевает что мы проверим и вернём результат в каком то виде... у тебя же идет выкидывание исключения... что нормально, но метод в таком случае лучше назвать честно:
`throwIfEmailNotUnique`

2022-10-16 15:12 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
> +        return UserMapper.toUserDto(userRepository.update(updatedUser));
Статики можно заимпортить заранее и получить немного более удобный код.

```
import static ru.practicum.shareit.user.UserMapper.toUserDto;

...

return toUserDto(userRepository.update(updatedUser));
```

2022-10-16 15:12 UTC, FanaticFiz commented on src/main/resources/application.yml
> +spring:
Как тебе `yaml` ?

2022-10-17 16:10 UTC, Feirina commented on src/main/resources/application.yml
> +spring:
Прикольный, похож по структуре на саму java)

2022-10-17 16:13 UTC, merged