feat: добавить функциональность аренды вещей
Feirina/java-shareit pull request #2
Opened 2022-10-30 09:39 UTC by Feirina

refactor: хранение информации в памяти заменить на хранение в БД

2022-10-30 15:55 UTC, Frilock requested changes
Добрый вечер, оставил пару комментариев к вашей работе. Жду новую итерацию, если что пишите

2022-10-30 15:55 UTC, Frilock commented on src/main/resources/schema.sql
> +    email VARCHAR(512) NOT NULL,
Смотрите, общий комментарий по скрипту и модели данных. Вы когда архитектуру БД планируете, нужно продумать размерность полей, то есть, например, поле код не должно иметь стандартный размер в 255, а его можно сделать, например, в 50 символов, а вот для описание нужно больше места, поэтому логичнее под данную колонку выделить, например, 1000. 
Кроме того, после того как Вы все указали в скрипте, тоже самое нужно сделать в аннотации Column для классов моделей. Указать размерность поля, а также дополнительные флаги, например, nullable = false.

2022-10-30 15:55 UTC, Frilock commented on src/main/java/ru/practicum/shareit/booking/repository/BookingRepository.java
> +    List<Booking> findAllByBooker_IdAndItem_IdAndStatusEqualsAndEndIsBefore(Long bookerId, Long itemId,
По идее все таки лучше camelCase следовать и в запросах, то есть подчеркивание можно убрать

2022-10-30 15:55 UTC, Frilock commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        if (item.getOwner().getId().equals(userId)) {
а owner обязательное поле? null тут не получим?

2022-10-30 15:55 UTC, Frilock commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        if (booking.getEnd().isBefore(booking.getStart())) {
Аналогично, тут booking.getEnd null не вернет?

2022-10-30 15:55 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/repository/CommentRepository.java
> +    List<Comment> findAllByItem_Id(Long itemId);
Давайте тоже camelCase использовать

2022-10-30 15:55 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +            itemDto.setLastBooking(bookingRepository.findAllByItem_IdOrderByStartAsc(itemDto.getId()).isEmpty() ?
А мы не можем эти 2 запроса в 1 объединить, чтобы какой то объект возвращать с последней и первой книгой? Чтобы не делать лишних запросов к базе

2022-10-30 15:55 UTC, Frilock commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
> +            updatedUser.setName(userDto.getName());
Я бы все таки посоветовал заменить на Optional.ofNullable(userDto.getName).ifPresent(updatedUser.setName)
Выглядит более компактно

2022-10-30 19:11 UTC, Feirina commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        if (item.getOwner().getId().equals(userId)) {
по идее нет, при создании вещи поле owner заполняется по переданному заголовку и проверяется, что такой юзер существует

2022-10-30 19:16 UTC, Feirina commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        if (booking.getEnd().isBefore(booking.getStart())) {
Нет, при создании booking идет проверка валидации полей star и end, но добавлю еще и в базу ограничение с not null

2022-10-30 20:28 UTC, Feirina commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +            itemDto.setLastBooking(bookingRepository.findAllByItem_IdOrderByStartAsc(itemDto.getId()).isEmpty() ?
Как смогла заменила, но выглядит как-то так себе

2022-10-31 09:45 UTC, Frilock approved these changes
Принял, по поводу запросов, предлагаю вернуться к изначальному варианту, я немного другое имел ввиду, но думаю не критично

2022-10-31 09:45 UTC, Frilock commented on src/main/java/ru/practicum/shareit/request/model/ItemRequest.java
>      @ManyToOne()
Пустые скобки не нужны

2022-10-31 09:45 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +            itemDto.setLastBooking(bookingRepository.findAllByItem_IdOrderByStartAsc(itemDto.getId()).isEmpty() ?
Да, предлагаю вернуться к изначальному варианту. Я немного другое имел ввиду, но думаю, что не критично

2022-11-03 21:37 UTC, merged